# Generated by Django 3.2.5 on 2021-08-30 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('store_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.storetype')),
            ],
        ),
    ]
