# Generated by Django 3.2.5 on 2021-08-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_storeinfo_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='business_account',
            field=models.ImageField(blank=True, null=True, upload_to='business_account'),
        ),
    ]
