# Generated by Django 3.2.5 on 2021-08-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0004_storeinfo_business_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_type', models.CharField(max_length=20)),
            ],
        ),
    ]
