# Generated by Django 3.2.5 on 2021-08-30 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystore', '0005_subscribetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_img', models.ImageField(upload_to='bay_image')),
                ('active', models.BooleanField(default=False)),
                ('subscribetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.subscribetype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
