# Generated by Django 3.2.5 on 2021-08-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0006_subscribestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='store_slug',
            field=models.SlugField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
