# Generated by Django 3.2.5 on 2021-09-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_coment_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
